// Generated by gencpp from file camera_current_pos/camera_current_pos.msg
// DO NOT EDIT!


#ifndef CAMERA_CURRENT_POS_MESSAGE_CAMERA_CURRENT_POS_H
#define CAMERA_CURRENT_POS_MESSAGE_CAMERA_CURRENT_POS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float64MultiArray.h>

namespace camera_current_pos
{
template <class ContainerAllocator>
struct camera_current_pos_
{
  typedef camera_current_pos_<ContainerAllocator> Type;

  camera_current_pos_()
    : TransitionMatrix()
    , FactorDepth(0.0)
    , RelativeDepth(0.0)
    , sin2Angles(0.0)
    , cos2Angles(0.0)  {
    }
  camera_current_pos_(const ContainerAllocator& _alloc)
    : TransitionMatrix(_alloc)
    , FactorDepth(0.0)
    , RelativeDepth(0.0)
    , sin2Angles(0.0)
    , cos2Angles(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float64MultiArray_<ContainerAllocator>  _TransitionMatrix_type;
  _TransitionMatrix_type TransitionMatrix;

   typedef double _FactorDepth_type;
  _FactorDepth_type FactorDepth;

   typedef double _RelativeDepth_type;
  _RelativeDepth_type RelativeDepth;

   typedef double _sin2Angles_type;
  _sin2Angles_type sin2Angles;

   typedef double _cos2Angles_type;
  _cos2Angles_type cos2Angles;




  typedef boost::shared_ptr< ::camera_current_pos::camera_current_pos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera_current_pos::camera_current_pos_<ContainerAllocator> const> ConstPtr;

}; // struct camera_current_pos_

typedef ::camera_current_pos::camera_current_pos_<std::allocator<void> > camera_current_pos;

typedef boost::shared_ptr< ::camera_current_pos::camera_current_pos > camera_current_posPtr;
typedef boost::shared_ptr< ::camera_current_pos::camera_current_pos const> camera_current_posConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera_current_pos::camera_current_pos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera_current_pos::camera_current_pos_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace camera_current_pos

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'camera_current_pos': ['/home/liuzhenkun/work/catkin_ws/src/camera_current_pos/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::camera_current_pos::camera_current_pos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera_current_pos::camera_current_pos_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_current_pos::camera_current_pos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_current_pos::camera_current_pos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_current_pos::camera_current_pos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_current_pos::camera_current_pos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera_current_pos::camera_current_pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "43d63e47b8948a41f18206bf9dcd71ed";
  }

  static const char* value(const ::camera_current_pos::camera_current_pos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x43d63e47b8948a41ULL;
  static const uint64_t static_value2 = 0xf18206bf9dcd71edULL;
};

template<class ContainerAllocator>
struct DataType< ::camera_current_pos::camera_current_pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera_current_pos/camera_current_pos";
  }

  static const char* value(const ::camera_current_pos::camera_current_pos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera_current_pos::camera_current_pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float64MultiArray TransitionMatrix\n\
float64 FactorDepth #绝对深度\n\
float64 RelativeDepth  #相对深度\n\
float64 sin2Angles #从sin算出来的角度\n\
float64 cos2Angles #从cos算出来的角度\n\
\n\
================================================================================\n\
MSG: std_msgs/Float64MultiArray\n\
# Please look at the MultiArrayLayout message definition for\n\
# documentation on all multiarrays.\n\
\n\
MultiArrayLayout  layout        # specification of data layout\n\
float64[]         data          # array of data\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/MultiArrayLayout\n\
# The multiarray declares a generic multi-dimensional array of a\n\
# particular data type.  Dimensions are ordered from outer most\n\
# to inner most.\n\
\n\
MultiArrayDimension[] dim # Array of dimension properties\n\
uint32 data_offset        # padding elements at front of data\n\
\n\
# Accessors should ALWAYS be written in terms of dimension stride\n\
# and specified outer-most dimension first.\n\
# \n\
# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n\
#\n\
# A standard, 3-channel 640x480 image with interleaved color channels\n\
# would be specified as:\n\
#\n\
# dim[0].label  = \"height\"\n\
# dim[0].size   = 480\n\
# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n\
# dim[1].label  = \"width\"\n\
# dim[1].size   = 640\n\
# dim[1].stride = 3*640 = 1920\n\
# dim[2].label  = \"channel\"\n\
# dim[2].size   = 3\n\
# dim[2].stride = 3\n\
#\n\
# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n\
\n\
================================================================================\n\
MSG: std_msgs/MultiArrayDimension\n\
string label   # label of given dimension\n\
uint32 size    # size of given dimension (in type units)\n\
uint32 stride  # stride of given dimension\n\
";
  }

  static const char* value(const ::camera_current_pos::camera_current_pos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera_current_pos::camera_current_pos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.TransitionMatrix);
      stream.next(m.FactorDepth);
      stream.next(m.RelativeDepth);
      stream.next(m.sin2Angles);
      stream.next(m.cos2Angles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct camera_current_pos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera_current_pos::camera_current_pos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera_current_pos::camera_current_pos_<ContainerAllocator>& v)
  {
    s << indent << "TransitionMatrix: ";
    s << std::endl;
    Printer< ::std_msgs::Float64MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.TransitionMatrix);
    s << indent << "FactorDepth: ";
    Printer<double>::stream(s, indent + "  ", v.FactorDepth);
    s << indent << "RelativeDepth: ";
    Printer<double>::stream(s, indent + "  ", v.RelativeDepth);
    s << indent << "sin2Angles: ";
    Printer<double>::stream(s, indent + "  ", v.sin2Angles);
    s << indent << "cos2Angles: ";
    Printer<double>::stream(s, indent + "  ", v.cos2Angles);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_CURRENT_POS_MESSAGE_CAMERA_CURRENT_POS_H
